EXTRACTION_SCHEMA = {
    "type": "object",
    "properties": {
        "project_name": {"type": "string"},
        "procurement_type": {"type": "string", "enum": ["goods"]},
        "budget_amount": {"type": "number", "minimum": 0},
        "currency": {"type": "string"},
        "method": {"type": "string", "enum": ["public_tender"]},
        "delivery_days": {"type": "integer", "minimum": 0},
        "warranty_months": {"type": "integer", "minimum": 0},
        "payment_terms": {"type": "string"},
        "delivery_batches": {"type": "integer", "minimum": 1},
        "acceptance_standard": {"type": "string"},
        "qualification_requirements": {
            "type": "array",
            "items": {"type": "string"},
        },
        "evaluation_method": {"type": "string"},
        "technical_requirements": {
            "type": "array",
            "items": {"type": "string"},
        },
        "special_terms": {
            "type": "array",
            "items": {"type": "string"},
        },
        "missing_fields": {
            "type": "array",
            "items": {"type": "string"},
        },
        "clarification_questions": {
            "type": "array",
            "items": {"type": "string"},
        },
    },
    "required": [
        "project_name",
        "procurement_type",
        "budget_amount",
        "currency",
        "method",
        "delivery_days",
        "warranty_months",
        "payment_terms",
        "delivery_batches",
        "acceptance_standard",
        "qualification_requirements",
        "evaluation_method",
        "technical_requirements",
        "special_terms",
        "missing_fields",
        "clarification_questions",
    ],
    "additionalProperties": False,
}
